apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: default-builder
spec:
  serviceAccount: harbor-service-account
  tag: harbor.${domain}/library/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/dotnet-core