#@ load("@ytt:overlay", "overlay")
#@data/values
---
#!
#! THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
#!
#! Copy this file to your GitOps repo in the config-custom directory.
#!
#@overlay/match missing_ok=True
aws:
  #! Set credentials for AWS Route53.
  #@overlay/match missing_ok=True
  route53:
    region: ${aws_region}
    accessKey: ${aws_dns_challenge_access}
    secretKey: ${aws_dns_challenge_secret}
    hostedZoneId: ${aws_zone_id}
