apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-gitops-sa
  namespace: tanzu-gitops
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-gitops-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-gitops-role-binding
subjects:
- kind: ServiceAccount
  name: tanzu-gitops-sa
  namespace: tanzu-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-gitops-role
